version: 2

sources:
  - name: raw
    schema: raw

    tables:
      - name: raw_rooms
      - name: raw_tenancies
      - name: raw_properties

models:

  - name: stg_properties

    columns:

      - name: property_id
        tests:
          - unique
          - not_null


      - name: property_name
        tests:
          - not_null



  - name: stg_rooms

    columns:

      - name: room_id
        tests:
          - unique
          - not_null


      - name: property_id
        tests:
          - not_null



  - name: stg_tenancies

    columns:

      - name: tenancy_id
        tests:
          - unique
          - not_null


      - name: room_id
        tests:
          - not_null